# Data configs
# Only change this path and everything updates automatically
user_path: '/Users/dimitriosmavrofrydis/Projects/Python/CACD_Project'

# Network Configs
ngf: 32
ndf: 32
n_blocks: 9

# Loss configs:
adv_weight: 2
cycle_weight: 10
identity_weight: 7

# Optimizer configs:
lr: 0.0001
weight_decay: 0.0001

# Training configs:
img_size: 400
batch_size: 4
num_workers: 4
epochs: 1
gpus: 0